CREATE DATABASE [mmm]
    CONTAINMENT = PARTIAL
    ON  PRIMARY
    ( NAME = N'mmm', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\mmm.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
    LOG ON
    ( NAME = N'mmm_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\mmm_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [mmm] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [mmm] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [mmm] SET ANSI_NULLS OFF
GO
ALTER DATABASE [mmm] SET ANSI_PADDING OFF
GO
ALTER DATABASE [mmm] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [mmm] SET ARITHABORT OFF
GO
ALTER DATABASE [mmm] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [mmm] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [mmm] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [mmm] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [mmm] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [mmm] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [mmm] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [mmm] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [mmm] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [mmm] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [mmm] SET  DISABLE_BROKER
GO
ALTER DATABASE [mmm] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [mmm] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [mmm] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [mmm] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [mmm] SET  READ_WRITE
GO
ALTER DATABASE [mmm] SET RECOVERY FULL
GO
ALTER DATABASE [mmm] SET  MULTI_USER
GO
ALTER DATABASE [mmm] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [mmm] SET DEFAULT_FULLTEXT_LANGUAGE = 1033
GO
ALTER DATABASE [mmm] SET DEFAULT_LANGUAGE = 1033
GO
ALTER DATABASE [mmm] SET NESTED_TRIGGERS = ON
GO
ALTER DATABASE [mmm] SET TRANSFORM_NOISE_WORDS = OFF
GO
ALTER DATABASE [mmm] SET TWO_DIGIT_YEAR_CUTOFF = 2049
GO
ALTER DATABASE [mmm] SET TARGET_RECOVERY_TIME = 60 SECONDS
GO
ALTER DATABASE [mmm] SET DELAYED_DURABILITY = DISABLED
GO
USE [mmm]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [mmm]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [mmm] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO
